# Generated by Django 3.1.1 on 2020-09-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0001_initial'),
        ('protests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='protest',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='protests.protest'
            ),
        ),
    ]
