# Generated by Django 3.1.1 on 2020-09-25 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protests', '0002_auto_20200925_0616'),
        ('participant', '0003_auto_20200925_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='protest',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participants',
                to='protests.protest',
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='participating_in',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
