# Generated by Django 3.1.1 on 2020-09-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Protest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('slug', models.SlugField(max_length=200)),
                ('venue_lat', models.FloatField(help_text='Venue latitude.')),
                ('venue_long', models.FloatField(help_text='Venue longitude.')),
                (
                    'description',
                    models.TextField(help_text='Details about the protest.'),
                ),
                (
                    'datetime',
                    models.DateTimeField(help_text='Date and time for protest.'),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of organisation or event.', max_length=250
                    ),
                ),
            ],
        ),
    ]
