# Generated by Django 3.1.1 on 2020-09-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Protest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('venue_lat', models.BigIntegerField()),
                ('venue_long', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=200)),
                (
                    'description',
                    models.TextField(help_text='Details about the protest.'),
                ),
                (
                    'datetime',
                    models.DateTimeField(help_text='Date and time for protest.'),
                ),
            ],
        ),
    ]
