# Generated by Django 3.1.1 on 2020-09-24 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protest',
            name='organizer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='protest',
            index=models.Index(fields=['slug'], name='protests_pr_slug_1f2372_idx'),
        ),
    ]
